openai:
  model: gpt-3.5-turbo
  api:
    # REPLACE KEY WITH A VALID OPENAI API KEY
    # reference: https://platform.openai.com/account/api-keys
    key: XXX-XXXXXXXX
    url: https://api.openai.com/v1/chat/completions